-- ============================================================================
-- VAXLAB MÉXICO — Preguntas semilla
-- Cada pregunta está construida EXCLUSIVAMENTE con contenido verificado de:
--   [HTML] evidencia_vacunacion_mexico_2026.html
--   [PDF]  INMUNIZACIONES_Y_ENVM-2.pdf
-- El campo source_reference cita la fuente exacta.
-- ============================================================================

insert into questions (category, difficulty, question, option_a, option_b, option_c, option_d, correct_option, explanation, source_reference, time_limit_seconds) values

-- ===== ROUND 1 — IMMUNOLOGY =====
('immunology','recall','¿Qué complejo presenta antígeno a los linfocitos CD8+ citotóxicos?','CMH-I','CMH-II','Complemento C3','Receptor Fc','A','Las células dendríticas presentan péptidos vía CMH-I a linfocitos CD8+ citotóxicos.','PDF, sección 3 — Inmunología Avanzada de la Vacunación',10),
('immunology','recall','¿Qué complejo presenta antígeno a los linfocitos CD4+ cooperadores?','CMH-I','CMH-II','TCR','BCR','B','CMH-II presenta péptidos a linfocitos CD4+ cooperadores.','PDF, sección 3 — Inmunología Avanzada de la Vacunación',10),
('immunology','comprehension','¿Dónde ocurre la cooperación T-B que madura la afinidad de los anticuerpos?','En el bazo únicamente','En los centros germinales de los ganglios linfáticos','En la médula ósea roja','En el timo','B','La cooperación T-B en los centros germinales induce maduración de afinidad y cambio de clase isotípica.','PDF, sección 3',10),
('immunology','recall','¿Dónde se alojan las células plasmáticas de larga vida y los linfocitos de memoria?','En el hígado','En el nicho óseo (médula ósea)','En el epitelio intestinal','En el tejido adiposo','B','El texto describe el "Nicho Óseo" como sitio de células plasmáticas de larga vida y B/T de memoria.','HTML, sección 2 — Cascada Inmunológica Post-Vacunal',10),
('immunology','comprehension','La inmunidad innata se caracteriza principalmente por ser:','Específica y de memoria permanente','Rápida y carente de especificidad','Exclusiva de los linfocitos T','Dependiente de anticuerpos IgG','B','La inmunidad innata es una respuesta biológica veloz y carente de especificidad.','PDF, Importancia Clínica de la Inmunidad y la Vacunación',10),
('immunology','comprehension','¿Qué distingue principalmente a la inmunidad adaptativa de la innata?','Que no usa células','Que establece memoria inmunológica permanente','Que actúa en segundos','Que no requiere linfocitos','B','La inmunidad adquirida se caracteriza por su precisión molecular y su habilidad de establecer memoria permanente.','PDF, Inmunidad Adquirida',10),
('immunology','application','Un paciente con inmunidad híbrida (infección previa + vacuna) muestra, a los 11 meses, una efectividad contra hospitalización por COVID-19 severo de aproximadamente:','50%','70%','>95%','10%','C','Bobrovitz et al. (2023): inmunidad híbrida confiere >95% de protección sostenida a los 11 meses.','HTML — KPI "Duración Memoria" / Bobrovitz et al., Lancet Infect Dis (2023)',10),
('immunology','recall','Las células T CD4+ y CD8+ de memoria permanecen estables, según la evidencia, por al menos:','1 mes','12 meses','1 semana','No permanecen estables','B','Sette & Crotty (2022): la memoria T CD4+/CD8+ permanece estable >12 meses.','HTML — Literatura: Sette A., Crotty S., Nat Rev Immunol (2022)',10),

-- ===== ROUND 2 — VACCINES =====
('vaccines','recall','¿Qué tipo de vacuna está contraindicada en inmunodepresión severa o post-trasplante reciente?','Inactivadas','Virus atenuados','Subunidades proteicas','Ninguna lo está','B','Tabla 2 del PDF: las vacunas de virus atenuados están contraindicadas en inmunodepresión severa o post-TPH reciente.','PDF, Tabla 2 — Tipos de Vacuna e Interacción con el Sistema Hematopoyético',10),
('vaccines','comprehension','¿Cuál es el mecanismo inmunológico principal de las vacunas inactivadas/subunidades?','Infección subclínica activa','Presentación antigénica exógena vía CMH-II','Replicación viral controlada','Transferencia pasiva de anticuerpos','B','Tabla 2 del PDF describe la presentación antigénica exógena al CMH-II como mecanismo de las inactivadas/subunidades.','PDF, Tabla 2',10),
('vaccines','comprehension','Las vacunas de virus atenuados generan inmunidad principalmente mediante:','Infección subclínica que estimula inmunidad celular y humoral robusta','Bloqueo directo de receptores virales','Neutralización química del patógeno','Estimulación exclusiva de neutrófilos','A','Tabla 2 del PDF: infección subclínica con inmunidad celular y humoral robusta.','PDF, Tabla 2',10),
('vaccines','application','Un paciente recibió un trasplante de progenitores hematopoyéticos (TPH) hace 2 meses. ¿Qué tipo de vacuna debe evitarse en este momento?','Inactivadas','Virus atenuados','Ambas por igual','Ninguna, puede recibir cualquiera','B','Las vacunas vivas atenuadas están contraindicadas en el post-TPH reciente por riesgo de infección sistémica descontrolada.','PDF, Tabla 2 + HTML, Protocolo HSCT',10),
('vaccines','recall','¿Qué porcentaje de pacientes con Artritis Reumatoide desarrolló respuesta de anticuerpos suficiente tras el esquema de vacunación COVID-19?','54%','68.2%','88.1%','95%','C','González-Serna et al. (2024): 88.1% de seroconversión en Artritis Reumatoide.','HTML — KPI "Respuesta Autoinmunidad" / González-Serna et al. (2024)',10),
('vaccines','recall','¿Qué efectividad mostró la vacuna recombinante contra Herpes Zóster (RZV) en receptores de trasplante hematopoyético?','88.1%','54%','68.2%','79.9%','C','Silva-Pinto et al. (2024-2025): 68.2% de efectividad de RZV en receptores HSCT.','HTML — KPI "Trasplante HSCT" / Silva-Pinto et al.',10),

-- ===== ROUND 3 — MÉXICO =====
('mexico','recall','¿Qué vacuna se aplica al nacimiento para prevenir tuberculosis meníngea?','Hepatitis B','BCG','Hexavalente','SRP','B','BCG se aplica como dosis única al nacer, contra tuberculosis meníngea.','HTML, Cronograma Oficial — Nacimiento',10),
('mexico','recall','La vacuna Hexavalente acelular se aplica en 3 dosis, a los:','2, 4 y 6 meses','1, 2 y 3 meses','6, 12 y 18 meses','Al nacer únicamente','A','Hexavalente acelular: 3 dosis a los 2, 4 y 6 meses.','HTML, Cronograma Oficial — 2, 4 y 6 Meses',10),
('mexico','comprehension','¿Cuál es la cobertura nacional de la 1ª dosis de SRP en México, según la investigación?','95%','84.2%','79.9%','68.2%','C','Cobertura SRP1: 79.9%, por debajo de la meta nacional/OMS de 95%.','HTML — KPI "Cobertura SRP México" / Informes de Salud, Cámara de Diputados (2026)',10),
('mexico','recall','¿A qué edad se aplica la 2ª dosis (refuerzo obligatorio) de SRP?','12 meses','18 meses','24 meses','4 años','B','SRP 2ª dosis a los 18 meses, refuerzo obligatorio de la 1ª (12 meses).','HTML, Cronograma Oficial — 12 y 18 Meses',10),
('mexico','comprehension','¿A qué población prioriza la vacuna VPH en el esquema mexicano, según la investigación?','Niños de 0-2 años','Niñas de 10-14 años / 5º de primaria','Adultos mayores','Mujeres embarazadas','B','VPH dirigida a niñas de 10-14 años / 5º de primaria.','HTML, Cronograma Oficial — Adolescentes y Adultos',10),
('mexico','application','Un lactante de 4 meses acude a su cita de vacunación de rutina en México. Según el esquema, ¿qué vacunas le corresponden?','Solo SRP','Hexavalente (2ª dosis), Rotavirus y Neumococo (2ª dosis)','Solo BCG','VPH','B','A los 4 meses corresponden la 2ª dosis de Hexavalente, Rotavirus y la 2ª dosis de Neumococo conjugada.','HTML, Cronograma Oficial — 2, 4 y 6 Meses',10),
('mexico','recall','¿Cuántas dosis de biológicos distribuyó el IMSS en la campaña invernal (influenza + COVID-19 + neumococo) mencionada en la investigación?','Más de 5 millones','Más de 16.5 millones','Más de 1 millón','Más de 100 millones','B','La meta institucional contempla más de 16.5 millones de dosis combinadas.','HTML, Contexto y Hallazgos Epidemiológicos',10),
('mexico','comprehension','¿Qué porcentaje de adherencia a esquemas completos de VPH se reportó en cohortes urbanas de México?','50%','82%','95%','30%','B','Soto-De León et al. (2023): adherencia de 82% con esquemas simplificados en escuelas.','HTML — Literatura: Soto-De León S. et al. (2023)',10),

-- ===== ROUND 4 — CLINICAL DECISION =====
('clinical','clinical_case','Un paciente recibió un trasplante de progenitores hematopoyéticos hace 4 meses. ¿Qué tipo de vacunas puede empezar a recibir?','Virus vivos atenuados (SRP)','Vacunas inactivadas (Influenza, COVID-19, Neumococo, Hexavalente/Tdap)','Ninguna vacuna por 2 años','Solo vacunas orales','B','Entre 3 y 6 meses post-trasplante se inician las vacunas inactivadas; las APCs están en reactivación.','HTML, Protocolo de Reinicio Inmunológico HSCT — "3 a 6 Meses"',15),
('clinical','clinical_case','El mismo paciente, a los 8 meses post-trasplante, podría recibir adicionalmente:','SRP y Varicela (vivos atenuados)','RZV (Herpes Zóster recombinante)','Ninguna vacuna adicional','BCG','B','Entre 6 y 12 meses post-trasplante corresponde la vacuna RZV (68.2% de efectividad).','HTML, Protocolo HSCT — "6 a 12 Meses"',15),
('clinical','clinical_case','¿Cuándo podría este paciente recibir finalmente SRP o Varicela (vivos atenuados)?','A los 6 meses','Nunca','Después de 24 meses, sin inmunosupresores y sin EICH activa','A los 3 meses','C','Los vivos atenuados solo se indican >24 meses post-trasplante, sin inmunosupresión y sin enfermedad injerto contra huésped.','HTML, Protocolo HSCT — ">24 Meses" + PDF, Tabla 2 (contraindicación en inmunodepresión severa)',15),
('clinical','clinical_case','¿Por qué las vacunas vivas atenuadas son especialmente riesgosas en el post-trasplante reciente?','Porque no generan ninguna respuesta inmune','Porque pueden causar infección sistémica descontrolada en un sistema inmunocomprometido','Porque son más caras','Porque requieren refrigeración especial','B','El PDF indica que están contraindicadas en inmunodepresión severa por el riesgo de infección sistémica descontrolada.','PDF, Tabla 2 — Tipos de Vacuna e Interacción con el Sistema Hematopoyético',15)
;
